packages:
  - playground/*
  - packages/*
  - packages/*/*
  - .docs
catalog:
  '@antfu/eslint-config': ^4.11.0
  '@babel/traverse': ^7.27.0
  '@clack/prompts': ^0.10.0
  '@egoist/tailwindcss-icons': ^1.9.0
  '@floating-ui/dom': ^1.6.13
  '@floating-ui/utils': ^0.2.9
  '@floating-ui/vue': ^1.1.6
  '@iconify-json/ph': ^1.2.2
  '@iconify/vue': ^4.3.0
  '@nuxt/kit': ^3.16.1
  '@nuxt/schema': ^3.16.1
  '@oku-ui/motion': ^0.4.3
  '@radix-ui/colors': ^3.0.0
  '@shikijs/vitepress-twoslash': ^3.2.1
  '@stackblitz/sdk': ^1.11.0
  '@storybook/addon-essentials': ^8.6.10
  '@storybook/addon-interactions': ^8.6.10
  '@storybook/addon-links': ^8.6.10
  '@storybook/blocks': ^8.6.10
  '@storybook/testing-library': ^0.2.2
  '@storybook/vue3': ^8.6.10
  '@storybook/vue3-vite': ^8.6.10
  '@testing-library/vue': ^8.1.0
  '@tsconfig/node20': ^20.1.5
  '@types/babel__traverse': ^7.20.7
  '@types/jsdom': ^21.1.7
  '@types/markdown-it': ^14.1.2
  '@types/node': ^22.13.14
  '@vitejs/plugin-vue': ^5.2.3
  '@vitejs/plugin-vue-jsx': ^4.1.2
  '@vitest/coverage-v8': ^3.0.9
  '@vue/test-utils': ^2.4.6
  aria-hidden: ^1.2.4
  autoprefixer: ^10.4.21
  bumpp: ^10.1.0
  changelogen: ^0.6.1
  chokidar: ^4.0.3
  chromatic: ^11.27.0
  codesandbox: ^2.2.3
  eslint: ^9.23.0
  eslint-plugin-storybook: ^0.12.0
  esno: ^4.8.0
  fast-glob: ^3.3.3
  filter-anything: ^4.0.3
  globby: ^14.1.0
  happy-dom: ^17.4.4
  jiti: ^2.4.2
  jsdom: ^26.0.0
  lint-staged: ^15.5.0
  markdown-it: ^14.1.0
  npm-run-all2: ^7.0.2
  nuxt: ^3.16.1
  nx: ^20.6.4
  ofetch: ^1.4.1
  pathe: ^2.0.3
  react: ^19.0.0
  react-dom: ^19.0.0
  rimraf: ^6.0.1
  simple-git-hooks: ^2.12.1
  storybook: ^8.6.10
  storybook-dark-mode: ^4.0.2
  tsup: ^8.4.0
  turbo: ^2.4.4
  typescript: ^5.8.2
  unbuild: ^3.5.0
  unplugin-vue-components: ^28.4.1
  vite: ^6.1.2
  vite-plugin-dts: ^4.5.3
  vite-plugin-externalize-deps: ^0.9.0
  vite-plugin-pages: ^0.32.5
  vite-tsconfig-paths: ^5.1.4
  vitepress: ^1.6.3
  vitest: ^3.0.9
  vitest-axe: 1.0.0-pre.5
  vitest-canvas-mock: ^0.3.3
  vue: ^3.5.13
  vue-router: ^4.5.0
  vue-sonner: ^1.3.0
  vue-tsc: ^2.2.8
